### ISSUE TITLE
Invalid elliptic curve point encoding in proof

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/plonk-verifier#11]
This happens with [this test](https://github.com/privacy-scaling-explorations/zkevm-chain/blob/3b933bcd4df22e4ec5833315a7a1c17953186c09/prover/tests/verifier.rs#L130)

```
---- autogen_aggregation_verifier stdout ----
thread 'autogen_aggregation_verifier' panicked at 'called `Result::unwrap()` on an `Err` value: Transcript(Other, "Invalid elliptic curve point encoding in proof")', /app/prover/src/aggregation_circuit.rs:213:26
```

**Comment by han0110** [comment]
Hey @pinkiebell, would you like to try to patch `halo2_proofs` with this branch https://github.com/han0110/halo2/tree/feature/configurable-instance-query?

I think in [`halo2@v2022_09_10`](https://github.com/privacy-scaling-explorations/halo2/tree/v2022_09_10) the instance commitments are still written to transcript, so `plonk-verifier` gets confused by some extra commitments there.

(hopefully these patching issues will never show again after both https://github.com/privacy-scaling-explorations/halo2/pull/96 and https://github.com/privacy-scaling-explorations/plonk-verifier/pull/5 are merged...)
