### ISSUE TITLE
ecPairing contract call returns 0

### ISSUE THREAD

**Issue by lazovicff** [privacy-scaling-explorations/plonk-verifier#34]
Smart contract reverts here: https://github.com/eigen-trust/protocol/blob/e51f43281fa87341cc5ecdb4a72a524af5c861d1/data/et_verifier.yul#L1738

How we generate code: https://github.com/eigen-trust/protocol/blob/e51f43281fa87341cc5ecdb4a72a524af5c861d1/circuit/src/verifier/mod.rs#L85-L114

The verification passes if we call evm directly with this function: https://github.com/eigen-trust/protocol/blob/e51f43281fa87341cc5ecdb4a72a524af5c861d1/circuit/src/verifier/mod.rs#L116-L134

**Comment by han0110** [comment]
Is the revertion happens to `TestCircuitPi`? If that's true, is there any test that I could run to reproduce this failure? That might provide more clue for me to find the bug, since `TestCircuitPi` looks okay for `snark-verifier`.

**Comment by lazovicff** [comment]
After doing more research, I realised that the problem is somewhere in our verifier wrapper: https://github.com/eigen-trust/protocol/blob/e51f43281fa87341cc5ecdb4a72a524af5c861d1/data/EtVerifierWrapper.sol

Sorry about this, will close the issue for now
