### ISSUE TITLE
Remove cargo patch sections and depend on the forks explicitly

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/plonk-verifier#8]
Patch sections are ignored if this crate is added as a dependency, hence remove the patch sections and depend on any forks without overriding.

**Comment by han0110** [comment]
I understand they will be ignore when this crate is used as dependency, but for this crate itself, we need some features from the patches for compiling and testing, so the patches are actually necessary.

Originally I used the forks as dependency directly, but I realized that then dependents need to patch multiple source (crate.io and github.com/han0110/halo2), so instead now I use patch to allow dependents to patch more easily (just crate.io). Does this approach make sense?

**Comment by pinkiebell** [comment]
So basically I need to copy the patch sections into `Cargo.toml` given that approach. I find that a bit annoying and a problem if I also use other crates that in turn depend on other versions of <crate>. Given that, I think it's much easier to directly declare the forks as dependency and *if* I need to change that I can explicitly override those (github.com/han0110/..).

**Comment by han0110** [comment]
I see, is that possible to wait for https://github.com/privacy-scaling-explorations/halo2/pull/96 merged? I think after that #5 will no longer need a patch anymore.

**Comment by pinkiebell** [comment]
No problem 👍
